manifest:
  remotes:
    # zmk official
    - name: zmkfirmware
      url-base: https://github.com/Nicell/zmk/tree/nice-view-custom-screen
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
